env: flex
runtime: nodejs
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
env_variables:
  APP_SERVER_PORT: 8080
  PUBLIC_SECRET_EXAMPLE: 'MONKEY'
beta_settings:
  cloud_sql_instances: ono-prod-216722:us-west2:ono-data
